import LinkPathname from "./components/link-pathname/link-pathname";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function OtherLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <header> this is header menu</header>
        <div>
          <LinkPathname />
        </div>
        {children}
        <footer>this is footer</footer>
        {/* <ActiveLink /> */}
      </body>
    </html>
  );
}
