import Link from "next/link";
import LinkPathname from "./components/link-pathname/link-pathname";
// import InputComponent from "./components/input-component/input-component";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function OtherLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <header> this is header menu</header>
        <div>
          <LinkPathname />
        </div>
        {children}
        <Link href="articles/breaking-news-123?lang=en">Read in English</Link>
        <Link href="articles/breaking-news-123?lang=fr">Read in French</Link>
        <Link href="client-articles/breaking-news-123?lang=fr">
          Read in French
        </Link>
        <footer>this is footer</footer>
        {/* <ActiveLink /> */}
      </body>
    </html>
  );
}
