export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function OtherLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <header> this is header menu</header>
        {children} <footer>this is footer</footer>
      </body>
    </html>
  );
}
