export const metadata = {
  title: "Next.js - Docs - Page",
  description: "Generated by Next.js - Docs - Page",
};

export default function DocLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <header> this is doc menu</header>
      {children} <footer>this is doc footer</footer>
    </>
  );
}
