import Counter from "./counter";

export const metadata = {
  title: "Next.js - Docs - counter Page",
  description: "Generated by Next.js - Docs - counter Page",
};

const CounterWrapper = () => {
  return (
    <div>
      <Counter />
    </div>
  );
};

export default CounterWrapper;
