import React from "react";

export const metadata = {
  title: "Next.js - Inside",
  description: "Generated by Next.js - Inside",
};

const ProductDetails = async ({
  params,
}: {
  params: Promise<{ productId: string }>;
}) => {
  const productId = await (await params).productId;
  return <div>page {productId}</div>;
};

export default ProductDetails;
